- CHANGES.txt
- plone/protect/auto.py
To fix compatibility with plone.app.blocks' ESI-rendering.
ESI transform must be the only transform, which returns bytes, and because Protect transform comes after that, it breaks blocks' ESI rendering on Plone 5.
The real reason, why ESI transform returns bytes, is that the ESI helpers in plone.tiles are implemented to work on bytestrings
https://github.com/plone/plone.tiles/blob/master/plone/tiles/esi.py
/cc https://github.com/plone/plone.app.blocks/issues/15
> Add ITransform.transformBytes for protect transform to fix compatibility

- CHANGES.rst
- plone/protect/configure.zcml
- plone/protect/monkey.py
Just let plone.protect do it's job also on zope root
> fix pluggable auth CSRF warnings on zope root

- plone/protect/auto.py
This isn't ideal, but Zope sessions write all the time so flagging those writes for CSRF checks hoses the entire site.
> don't worry about writes to session objects in the temporary storage

- README.rst
I added some minimal documentation for the `addTokenToUrl()` function.
Additionally, I took the liberty to reorder the three possible methods to allow writes on read in order of "ascending insecurity" (more secure to less secure):
- Adding a CSRF token to the URL
- Whitelisting a single object for writes
- Whitelisting the entire request
I also moved the previous section header for the `IDisableCSRFProtection` interface (`Allowing write on read programatically`) to apply for that whole section, and instead labeled the `IDisableCSRFProtection` method `Marking the entire request as safe`.
> README: Document addTokenToUrl()

- CHANGES.rst
- plone/protect/confirm.pt
- Makes title and description actually show up (using `fill-slot` instead of `define-slot`)
- Disables editable border
---
> Show title and description in @@confirm-action view, disable editable border

- CHANGES.rst
- plone/protect/auto.py
The handling for redirects introduced in @6348b574 leads to this traceback when a redirect is encountered:
```pytb
2015-11-02 11:58:49 ERROR plone.transformchain Unexpected error whilst trying to apply transform chain
Traceback (most recent call last):
File "/Users/lukasgraf/Plone/eggs/plone.transformchain-1.0.4-py2.7.egg/plone/transformchain/transformer.py", line 48, in __call__
newResult = handler.transformIterable(result, encoding)
File "/Users/lukasgraf/Plone/buildouts/plone/plone4/src/plone.protect/plone/protect/auto.py", line 163, in transformIterable
return self.transform(result, encoding)
File "/Users/lukasgraf/Plone/buildouts/plone/plone4/src/plone.protect/plone/protect/auto.py", line 267, in transform
root = result.tree.getroot()
AttributeError: 'list' object has no attribute …
```
> Make sure transforms don't fail on redirects

- CHANGES.rst
- plone/protect/auto.py
- plone/protect/utils.py
With https://github.com/plone/plone.contentrules/pull/4, which tries to fix a few write-on-read failures, we get errors like this:
```
'TestRequest' object has no attribute 'environ'
```
See for example:
http://jenkins.plone.org/job/pull-request-5.0/941/testReport/junit/plone.app.z3cform.tests.test_objectsubform/TestObjectSubForm/test_closest_content/
This pull request fixes this, plus a few more spots where this could happen though I did not see it yet.
> Test request missing environ

- CHANGES.txt
- plone/protect/authenticator.py
- plone/protect/interfaces.py
I though I had created a pull request already, but I was wrong.
This is needed for https://github.com/plone/buildout.coredev/pull/176 and is tested there. Plone 4.3 only.
This does ** not** add auto csrf protection. But it makes it easier to write code that works with both 2.x and 3.x. Put simply, it makes sure that trying to disable auto csrf protection on 2.x (which does not have it) does not fail.
> Add forward compatibility for auto protection in the 2.x branch

- CHANGES.rst
- plone/protect/auto.py
- plone/protect/configure.zcml
- plone/protect/protect.js
This adds an `X-CSRF-TOKEN` header to ajax requests.
Fixes https://github.com/plone/plone.protect/issues/42
To make it a bit easier to test this, I have created a `sample.js` and related code on branch https://github.com/plone/plone.protect/tree/maurits-add-protect-js-sample-test-dont-merge
That branch should definitely **not** be merged. Commit https://github.com/plone/plone.protect/commit/7c8f4340290e0b23eb93f20a1d26a0f6ac62fcb5 explains it.
> Added protect.js from plone4.csrffixes.

- CHANGES.rst
- plone/protect/configure.zcml
- plone/protect/monkey.py
The patch has been merged to `Products.CMFFormController` 3.0.7 (Plone
4.3 and 5.0) and 3.1.2 (Plone 5.1).
Note that we are not requiring those versions in our `setup.py`,
because the code in this package no longer needs it.
We actually never had Products.CMFFormController in our
install_requires, so it would seem strange to begin with that now that
the code that we needed the dependency for has been removed. :-)
This pull request makes it easier/possible to properly include the 20160830 hotfix in CMFFormController itself.
> Removed `RedirectTo` patch.

- CHANGES.rst
- plone/protect/auto.py
Avoid (unnoticed) error when refreshing lock in Plone 4,
plus a few other cases that were handled by plone4.csrffixes.
Fixes https://github.com/plone/plone.protect/issues/47
> Avoid regenerating image scale over and over in Plone 4.

- CHANGES.rst
- plone/protect/auto.py
... because it's already there. This would also make things easier for the Zope4 transition.
> use self.request instead of z.globalrequest

- CHANGES.rst
- plone/protect/configure.zcml
This avoids an error when calling it on a subsite.
Fixes issue #51.
> Allow `confirm-action` for all contexts, instead of only Plone Site

- CHANGES.rst
- plone/protect/auto.py
The `print_stack()` function does actually print the stack (to stdout), not return it. What we want to do here is use `format_stack` so that we can include the stack in the message.
```python
>>> import traceback
>>> value = traceback.print_stack()
File "<stdin>", line 1, in <module>
>>> print value
None
>>> value = traceback.format_stack()
>>> print value
['  File "<stdin>", line 1, in <module>\n']
```
> Fix logging to no longer write to stdout.

- CHANGES.rst
- plone/protect/auto.py
- plone/protect/tests/testAuto.py
if a text/html response does not contain any data (eg empty page for an ajax request)
we do not log a warning that no csrf token could be added
this fixes #15 
not sure if the tests actually add value since i did not find a way to check no warning message is logged.
> do not log a warning for empty responses

- CHANGES.rst
- plone/protect/auto.py
I'm not quite sure what changed, but I was seeing CSRF protection errors due to image scales being generated, and this seems to fix it.
> avoid CSRF warnings from updating image scales

- CHANGES.rst
- plone/protect/utils.py
- setup.py
This PR is for branch 3.x that I have just created. It is used by coredev 5.0 and 5.1. With `plone4.csrffixes` it should still be fine for Plone 4.3 as well.
For info on the breakage see mostly issue #74, and a bit #75.
This PR basically reverts PR #72 on branch 3.x, except commit 7edf02d3b16e5c6b03e1288ba1cecfe9bcb4761f which seems harmless (plus the changelog entry, which should remain for historical accuracy).
The py3 changes should remain on master, used by Plone 5.2. But I hope that it can be replaced by code that looks less scary. To quote a comment from the code: "It should probably be updated to use the decorator module."
> Revert py3 changes that cause possible SyntaxError

- CHANGES.rst
- setup.py
`cssselect` has been an extra of `lxml` since 2014.
https://github.com/lxml/lxml/commit/f601d017a344b337c071c9ebbcb9684e52055d59
refs, #79
> Fix package dependencies

- CHANGES.rst
- plone/protect/configure.zcml
- setup.py
It has been merged into Zope 4 itself.
> Remove five.globalrequest

- news/88.fixed
- plone/protect/tests/testAuto.py
- plone/protect/utils.py
- setup.py
Fixes issues with objects that have many annotations.
Closes #88
> When marking an OOBTree as safe, also mark its buckets as safe.

- setup.py
`configure.zcml` uses this dependency to load its `meta.zcml`.
> Add missing z3c.zcmlhook dependency

- news/122.bugfix
- plone/protect/subscribers.py
A few lines further we already have a check `if req:`, so this should already have been done here as well.
This probably only happens in tests, not in real world usage.
This is needed for an upcoming change in PAS.
See https://github.com/zopefoundation/Products.PluggableAuthService/pull/122#issuecomment-2791286070
Forward port of PR #128.
> In login event subscriber, do not fail if request is not found. [master]

- news/3953.breaking
- plone/protect/confirm.pt
This PR moves the plone.protect.confirm.pt template to plone.app.layout.viewlets
> Move plone protect to plone layout
